# MaidSafe CI script
#
language: cpp
compiler:
- gcc
os:
- linux
git:
    submodules: false
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- git checkout next
- git submodule foreach git checkout next
install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo add-apt-repository -y ppa:boost-latest/ppa
- sudo apt-get clean
- sudo apt-get update
- sudo apt-get install -y -f build-essential python-psutil libfuse-dev libicu-dev valgrind binutils-gold gcc-4.9 g++-4.9 python-dev
- wget http://www.cmake.org/files/v2.8/cmake-2.8.12.2.tar.gz
- tar xf cmake-2.8.12.2.tar.gz
- cd cmake-2.8.12.2
- ./bootstrap
- make
- sudo make install
- cd ..
- wget http://sourceforge.net/projects/boost/files/boost/1.57.0/boost_1_57_0.tar.bz2/download -O /tmp/boost.tar.bz2
- tar jxf /tmp/boost.tar.bz2
- mv boost_1_57_0 $PWD/boost-trunk
- export BOOST_ROOT="$PWD/boost-trunk"
- cd $BOOST_ROOT
- ./bootstrap.sh
- ./b2
before_script:
- cd ../..
- cmake -HMaidSafe -Bbuild_maidsafe -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=On -DCMAKE_CXX_COMPILER=g++-4.9 -DCMAKE_C_COMPILER=gcc-4.9
- cd build_maidsafe
script:
- make AllCommon
