# MaidSafe CI script - 20150227
#
language: cpp
compiler:
- gcc
os:
- linux
git:
    submodules: false
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- git checkout next
- git submodule foreach git checkout next
install:
#- sudo pip install cpp-coveralls
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#- sudo add-apt-repository -y ppa:afrank/boost was for libboost1.57-all-dev mlocate
- sudo apt-get clean
- sudo apt-get update
- sudo apt-get install -y -f build-essential python-psutil libfuse-dev libicu-dev valgrind binutils-gold gcc-4.9 g++-4.9 python-dev
- sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90
#- sudo updatedb
#- sudo locate libboost | grep /lib | grep -e ".a$"
- wget http://www.cmake.org/files/v2.8/cmake-2.8.12.2.tar.gz
- tar xf cmake-2.8.12.2.tar.gz
- cd cmake-2.8.12.2
- ./bootstrap
- make
- sudo make install
- cd ${TRAVIS_BUILD_DIR}
- wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
- tar xf lcov_1.11.orig.tar.gz
- sudo make -C lcov-1.11/ install
- gem install coveralls-lcov
- lcov --version
- g++ --version
before_script:
#- cd ..
- cmake -H. -Bbuild_maidsafe -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=On -DCMAKE_CXX_COMPILER=g++-4.9 -DCMAKE_C_COMPILER=gcc-4.9
- cd build_maidsafe
#- cd ${TRAVIS_BUILD_DIR}
# init coverage to 0 (optional)
#- lcov --directory . --zerocounters
script:
- make ExperThirdParty
after_success:
#- coveralls --exclude lib --exclude tests --gcov-options '\-lp' 
#- coveralls --exclude *boost* --gcov-options '\-lp'
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --capture --output-file coverage.info
- lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
- lcov --list coverage.info
- coveralls-lcov --repo-token DhZ4qXGIUBoW5P2MNUqGYfr6csZYqrxAi coverage.info
