# MaidSafe CI Script 20150313
#
language: cpp
compiler:
- gcc
os:
- linux
git:
    submodules: false
before_install:
- git checkout travis
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- git submodule foreach git checkout next
install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get clean
- sudo apt-get update
- sudo apt-get install -y -f build-essential python-psutil libfuse-dev libicu-dev valgrind binutils-gold gcc-4.9 g++-4.9 python-dev
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
- sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90
- wget http://www.cmake.org/files/v2.8/cmake-2.8.12.2.tar.gz
- tar xf cmake-2.8.12.2.tar.gz
- cd cmake-2.8.12.2
- ./bootstrap
- make
- sudo make install
- cd ${TRAVIS_BUILD_DIR}
- wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
- tar xf lcov_1.11.orig.tar.gz
- sudo make -C lcov-1.11/ install
- gem install coveralls-lcov
- lcov --version
- g++ --version
before_script:
- cmake -H. -Bbuild_maidsafe -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=On -DCMAKE_CXX_COMPILER=g++-4.9 -DCMAKE_C_COMPILER=gcc-4.9
- cd build_maidsafe
script:
- make ExperApi
after_success:
- cd ${TRAVIS_BUILD_DIR}
- lcov --compat-libtool --directory . --capture --output-file coverage.info
- lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
- lcov --list coverage.info
- coveralls-lcov --repo-token 0jLfwkcxCeVnPDTZNtUGwwiAbvaMD4ow2 coverage.info
